// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM4Qy6LMPbkYq3pOhhPCx_VFxI-BWE3aA',
    appId: '1:538081636421:web:8683d34e88c2276e5f732c',
    messagingSenderId: '538081636421',
    projectId: 'hypnotic-trees-347004',
    authDomain: 'hypnotic-trees-347004.firebaseapp.com',
    storageBucket: 'hypnotic-trees-347004.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXCIGSLKHXsiw12ww1Tld8RCkRmH-Y1A',
    appId: '1:538081636421:android:53548f3a8471f0155f732c',
    messagingSenderId: '538081636421',
    projectId: 'hypnotic-trees-347004',
    storageBucket: 'hypnotic-trees-347004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUayeuvAnofBXeEjreUlyPCnuw5MfTeQ',
    appId: '1:538081636421:ios:5ec43f86618bff715f732c',
    messagingSenderId: '538081636421',
    projectId: 'hypnotic-trees-347004',
    storageBucket: 'hypnotic-trees-347004.appspot.com',
    iosClientId: '538081636421-vttn3te0ps7le8dks7ntim5e1gf7qrri.apps.googleusercontent.com',
    iosBundleId: 'com.example.singalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVUayeuvAnofBXeEjreUlyPCnuw5MfTeQ',
    appId: '1:538081636421:ios:5ec43f86618bff715f732c',
    messagingSenderId: '538081636421',
    projectId: 'hypnotic-trees-347004',
    storageBucket: 'hypnotic-trees-347004.appspot.com',
    iosClientId: '538081636421-vttn3te0ps7le8dks7ntim5e1gf7qrri.apps.googleusercontent.com',
    iosBundleId: 'com.example.singalChatApp',
  );
}
